name: polglase.net.au
favicon: null
layout_spectrum: 0.4417991058435291
typography_spectrum: 0.7223463063128293
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3079259740188718
  lightness: 0.5711913041304797
  saturation: 0.17179503315128386
  rhythmicContrast: 0.6005649247672409
purpose: []
